### Ambil Semua Catatan
GET https://be-rest-311135974217.us-central1.run.app/api/notes

### Tambah Catatan Baru
POST https://be-rest-311135974217.us-central1.run.app/api/notes
Content-Type: application/json

{
    "judul": "APAYAK",
    "isi": "APAKEK"
}

### Update Catatan
PUT https://be-rest-311135974217.us-central1.run.app/api/notes/3
Content-Type: application/json

{
    "judul": "ITU LAH",
    "isi": "ADALAH POKOKNYA"
}

### Hapus Catatan
DELETE https://be-rest-311135974217.us-central1.run.app/api/notes/3